name: Clone and Zip Repository

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  ansible-deploy:
    runs-on: 
      - self-hosted  # Use self-hosted runner
      - Linux
      - X64  # Match the labels of your runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install zip utility (if not installed)
      - name: Install zip utility
        run: sudo apt-get update && sudo apt-get install -y zip

      # Step 3: Generate a unique timestamp and zip the repository
      - name: Zip the repository with a unique name
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')  # Generate a unique timestamp
          ZIP_NAME="unidq_$TIMESTAMP.zip"      # Create the unique zip file name
          zip -r /home/ubuntu/git/$ZIP_NAME .   # Zip the repository with the unique name

      # Step 4: Verify the zip file creation
      - name: List the contents of the target directory
        run: ls -l /home/ubuntu/git
