name: Run Ansible Playbook

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  ansible-deploy:
    runs-on: 
      - self-hosted
      - Linux
      - X64  # Match the labels of your runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create a Vault Password File
      - name: Create vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /tmp/vault_password

      # Step 3: Run the Ansible Playbook
      - name: Run Ansible Playbook
        run: |
          ansible-playbook --vault-password-file /tmp/vault_password web.yml
