name: Run Ansible Playbook on EC2 (Self-Hosted Runner)

on:
   workflow_dispatch:

jobs:
  ansible:
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Vault password for Ansible
      - name: Set up Vault password
        run: echo "${{ secrets.VAULT_PASSWORD }}" > vault-password.txt

      # Step 3: Debugging - Check vault-password.txt file
      - name: Check vault-password.txt contents
        run: cat vault-password.txt

      # Step 4: Check permissions of vault-password.txt
      - name: Check vault-password.txt permissions
        run: ls -l vault-password.txt

      # Step 5: Remove any extra spaces or newlines from the password file
      - name: Sanitize vault-password.txt
        run: sed -i 's/[[:space:]]*$//' vault-password.txt

      # Step 6: Run Ansible Playbook on EC2
      - name: Run Ansible Playbook on EC2
        run: |
          ansible-playbook --vault-password-file=vault-password.txt -i /home/ubuntu/code/inventory /home/ubuntu/code/web.yml
